CREATE TABLE Category(
ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
Name VARCHAR(250) NOT NULL,
Descricao VARCHAR(250)

CREATE TABLE Person(
ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
Name VARCHAR(250) NOT NULL,
Surname VARCHAR(250) NOT NULL
);

CREATE TABLE Purchase(
ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
ItemName VARCHAR(250) NOT NULL,
DateOfPurchase DATE NOT NULL,
PersonID INT NOT NULL,
CategoryID INT NOT NULL,
Price DOUBLE NOT NULL,
FOREIGN KEY (PersonID) REFERENCES Person(ID),
FOREIGN KEY (CategoryID) REFERENCES Category(ID));

CREATE TABLE Purchase(
ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
ItemName VARCHAR(250) NOT NULL,
DateOfPurchase DATE NOT NULL,
PersonID INT NOT NULL,
CategoryID INT NOT NULL,
Price DOUBLE NOT NULL,
FOREIGN KEY (PersonID) REFERENCES Person(ID) ON DELETE CASCADE
       ON UPDATE CASCADE,
FOREIGN KEY (CategoryID) REFERENCES Category(ID)ON DELETE CASCADE
       ON UPDATE CASCADE);



NETBEANS JAVADB

CREATE TABLE Category(
ID INT NOT NULL  PRIMARY KEY GENERATED ALWAYS AS IDENTITY
        (START WITH 1, INCREMENT BY 1),
Name VARCHAR(250) NOT NULL,
Descricao VARCHAR(250),
Total DOUBLE NOT NULL);

CREATE TABLE Person(
ID INT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY
        (START WITH 1, INCREMENT BY 1),
Name VARCHAR(250) NOT NULL,
Surname VARCHAR(250) NOT NULL
);

CREATE TABLE Purchase(
ID INT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY
        (START WITH 1, INCREMENT BY 1),
ItemName VARCHAR(250) NOT NULL,
DateOfPurchase DATE NOT NULL,
PersonID INT NOT NULL,
CategoryID INT NOT NULL,
Price DOUBLE NOT NULL,
FOREIGN KEY (PersonID) REFERENCES Person(ID),
FOREIGN KEY (CategoryID) REFERENCES Category(ID));


Select sum(Price) as Sumatorio, MONTH(DateOfPurchase) as Mes, CategoryID as Categoria from Purchase group by CategoryID ,MONTH(DateOfPurchase)
